/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as TransactionsBulkCreateRouteImport } from './routes/transactions.bulk-create'
import { Route as EntitiesBulkCreateRouteImport } from './routes/entities.bulk-create'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsBulkCreateRoute = TransactionsBulkCreateRouteImport.update({
  id: '/transactions/bulk-create',
  path: '/transactions/bulk-create',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesBulkCreateRoute = EntitiesBulkCreateRouteImport.update({
  id: '/entities/bulk-create',
  path: '/entities/bulk-create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entities/bulk-create': typeof EntitiesBulkCreateRoute
  '/transactions/bulk-create': typeof TransactionsBulkCreateRoute
  '/entities/': typeof EntitiesIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entities/bulk-create': typeof EntitiesBulkCreateRoute
  '/transactions/bulk-create': typeof TransactionsBulkCreateRoute
  '/entities': typeof EntitiesIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entities/bulk-create': typeof EntitiesBulkCreateRoute
  '/transactions/bulk-create': typeof TransactionsBulkCreateRoute
  '/entities/': typeof EntitiesIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/entities/bulk-create'
    | '/transactions/bulk-create'
    | '/entities/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/entities/bulk-create'
    | '/transactions/bulk-create'
    | '/entities'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/entities/bulk-create'
    | '/transactions/bulk-create'
    | '/entities/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EntitiesBulkCreateRoute: typeof EntitiesBulkCreateRoute
  TransactionsBulkCreateRoute: typeof TransactionsBulkCreateRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/bulk-create': {
      id: '/transactions/bulk-create'
      path: '/transactions/bulk-create'
      fullPath: '/transactions/bulk-create'
      preLoaderRoute: typeof TransactionsBulkCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/bulk-create': {
      id: '/entities/bulk-create'
      path: '/entities/bulk-create'
      fullPath: '/entities/bulk-create'
      preLoaderRoute: typeof EntitiesBulkCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EntitiesBulkCreateRoute: EntitiesBulkCreateRoute,
  TransactionsBulkCreateRoute: TransactionsBulkCreateRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
